/**
 * Multi-item grocery order workflow.
 *
 * State machine:
 *   new → ensure_address → preparing_preview → await_confirm
 *     → placing → completed
 *                 ↓
 *               failed / cancelled
 *
 * Single confirmation: cart + fees + total are presented together. The
 * user reviews everything in one message and replies "yes" / "no". The
 * preview is generated by provider.previewOrder({ confirmOrder: false })
 * so fees come from the live cart, not estimates.
 *
 * One quantity-1 line per query in the user's request. Mid-cart edits
 * (remove, change, requantify) are not implemented in v1 — replying with
 * a new query list re-starts the flow.
 *
 * State persists in agent_tasks(type='order') with kind='order_v3' to
 * avoid colliding with the legacy zepto_order_v2 state shape.
 */

import { and, desc, eq, gt, inArray } from 'drizzle-orm';
import { db } from '../../config/database.js';
import { agentTasks, users, type AgentTask } from '../../db/schema.js';
import {
  type GroceryProvider,
  GroceryProviderError,
  GroceryProviderNotConnectedError,
  type OrderPreview,
  type ProductOption,
  type SearchGroup,
} from '../../providers/grocery/index.js';
import { getGroceryProvider } from '../../providers/grocery/index.js';
import { escapeHtml } from '../../utils/html.js';
import { createLogger } from '../../utils/logger.js';

const log = createLogger('order-workflow');

// ─────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────

export type Phase =
  | 'new'
  | 'ensure_address'
  | 'await_address_choice'
  | 'preparing_preview'
  | 'await_confirm'
  | 'placing'
  | 'completed'
  | 'failed'
  | 'cancelled';

export interface CartLineState {
  query: string;
  productVariantId: string;
  storeProductId: string;
  name: string;
  packSize: string;
  pricePaise: number;
  quantity: number;
}

export interface AddressState {
  id: string;
  label: string;
}

export interface PreviewState {
  cartKey?: string;
  subtotalPaise: number;
  deliveryFeePaise: number;
  handlingFeePaise: number;
  totalPaise: number;
  etaMinutes?: number;
}

export interface PhaseTrace { phase: Phase; action: string; at: string; }
export interface PhaseError { phase: Phase; code: string; message: string; at: string; }

export interface OrderState {
  kind: 'order_v3';
  phase: Phase;
  /** Original queries with requested quantities, in user-stated order. */
  requests: OrderItemRequest[];
  /** Pending address candidates while we wait for the user's pick. */
  addressChoices?: AddressState[];
  unmatchedQueries: string[];
  address?: AddressState;
  cart?: CartLineState[];
  preview?: PreviewState;
  order?: { id?: string; placedAt: string };
  errors: PhaseError[];
  trace: PhaseTrace[];
  updatedAt: string;
}

export interface OrderItemRequest {
  query: string;
  quantity: number;
}

export interface OrderTurnInput {
  userId: string;
  message: string;
  /**
   * Structured items from the intent classifier — one entry per distinct
   * product the user wants, with quantity. If undefined or empty, this turn
   * is treated as a confirmation / continuation of an existing workflow.
   */
  orderItems?: OrderItemRequest[];
}

export interface WorkflowReply {
  text: string;
  finished?: boolean;
}

// ─────────────────────────────────────────────────────────────────────────
// Persistence
// ─────────────────────────────────────────────────────────────────────────

const WORKFLOW_TTL_MS = 30 * 60 * 1000;
const ACTIVE_STATUSES = ['active', 'waiting_user'] as const;

function blank(): OrderState {
  return {
    kind: 'order_v3',
    phase: 'new',
    requests: [],
    unmatchedQueries: [],
    errors: [],
    trace: [],
    updatedAt: new Date().toISOString(),
  };
}

function isOrderState(s: unknown): s is OrderState {
  return typeof s === 'object' && s !== null
    && (s as { kind?: unknown }).kind === 'order_v3';
}

async function load(userId: string): Promise<{ task: AgentTask; state: OrderState } | null> {
  const [task] = await db
    .select()
    .from(agentTasks)
    .where(
      and(
        eq(agentTasks.userId, userId),
        eq(agentTasks.type, 'order'),
        inArray(agentTasks.status, [...ACTIVE_STATUSES]),
        gt(agentTasks.expiresAt, new Date()),
      ),
    )
    .orderBy(desc(agentTasks.updatedAt))
    .limit(1);
  if (!task || !isOrderState(task.state)) return null;
  return { task, state: task.state };
}

async function save(userId: string, state: OrderState, existing?: AgentTask): Promise<void> {
  state.updatedAt = new Date().toISOString();
  const status =
    state.phase === 'completed' ? 'completed'
      : state.phase === 'cancelled' ? 'cancelled'
      : state.phase === 'failed' ? 'failed'
      : 'waiting_user';
  const expiresAt = status === 'waiting_user' ? new Date(Date.now() + WORKFLOW_TTL_MS) : null;

  if (existing) {
    await db
      .update(agentTasks)
      .set({
        status,
        state,
        expiresAt: expiresAt ?? existing.expiresAt,
        updatedAt: new Date(),
      })
      .where(eq(agentTasks.id, existing.id));
    return;
  }
  await db.insert(agentTasks).values({
    userId,
    type: 'order',
    status,
    state,
    expiresAt: expiresAt ?? new Date(Date.now() + WORKFLOW_TTL_MS),
  });
}

function trace(state: OrderState, phase: Phase, action: string): void {
  state.trace.push({ phase, action, at: new Date().toISOString() });
  if (state.trace.length > 40) state.trace.splice(0, state.trace.length - 40);
}
function recordError(state: OrderState, phase: Phase, code: string, message: string): void {
  state.errors.push({ phase, code, message: message.slice(0, 500), at: new Date().toISOString() });
  log.warn(`[phase=${phase}] ${code}: ${message}`);
}

// ─────────────────────────────────────────────────────────────────────────
// Intent / reply parsing
// ─────────────────────────────────────────────────────────────────────────

const CONFIRM_RE = /^(yes|y|yep|yeah|confirm|go ahead|order it|place it|do it|haan|haan ji|han|haa|sure|ok|okay|chalo|kar do|mangwa do|manga do|✅)\b/i;
const CANCEL_RE = /^(no|n|nope|nah|cancel|stop|don'?t|leave it|rehne do|mat karo|nahi|nahin|abort|✗|❌)\b/i;

function parseConfirm(text: string): 'yes' | 'no' | null {
  const t = text.trim();
  if (CONFIRM_RE.test(t)) return 'yes';
  if (CANCEL_RE.test(t)) return 'no';
  return null;
}


// ─────────────────────────────────────────────────────────────────────────
// Reply formatters
// ─────────────────────────────────────────────────────────────────────────

function rupees(paise: number): string {
  if (paise === 0) return '₹0';
  return `₹${(paise / 100).toFixed(paise % 100 === 0 ? 0 : 2)}`;
}

function presentPreviewReply(state: OrderState): string {
  const cart = state.cart ?? [];
  const pre = state.preview;
  if (!pre) return 'Preparing preview…';

  const lines = cart.map((l, i) => {
    const qty = l.quantity > 1 ? ` × ${l.quantity}` : '';
    const sub = `${escapeHtml(l.name)}${qty}`;
    const meta: string[] = [];
    if (l.packSize) meta.push(escapeHtml(l.packSize));
    if (l.pricePaise > 0) meta.push(`<b>${rupees(l.pricePaise * l.quantity)}</b>`);
    return `${i + 1}. ${sub}${meta.length ? ' · ' + meta.join(' · ') : ''}`;
  });

  const addr = state.address?.label ? ` to ${escapeHtml(state.address.label)}` : '';
  const eta = pre.etaMinutes ? `\n⏱ ETA ~${pre.etaMinutes} min` : '';
  const unmatched = state.unmatchedQueries.length
    ? `\n\n⚠️ Couldn't find: ${state.unmatchedQueries.map(escapeHtml).join(', ')}`
    : '';

  return [
    `<b>Cart preview</b>${addr}:`,
    '',
    lines.join('\n'),
    '',
    `Subtotal: <b>${rupees(pre.subtotalPaise)}</b>`,
    `Delivery: ${rupees(pre.deliveryFeePaise)}`,
    `Handling: ${rupees(pre.handlingFeePaise)}`,
    `<b>Total: ${rupees(pre.totalPaise)}</b> · COD${eta}${unmatched}`,
    '',
    'Reply <b>yes</b> to place, <b>no</b> to cancel.',
  ].join('\n');
}

function placedReply(state: OrderState): string {
  const total = state.preview?.totalPaise;
  const id = state.order?.id;
  const idLine = id ? `\nOrder id: <code>${escapeHtml(id)}</code>` : '';
  const totalLine = total ? ` for <b>${rupees(total)}</b>` : '';
  return `✅ Order placed${totalLine} on COD.${idLine}\n\nI'll update your pantry once it arrives 🍽️`;
}

// ─────────────────────────────────────────────────────────────────────────
// Phases
// ─────────────────────────────────────────────────────────────────────────

/**
 * Result discriminator for ensureAddress:
 *   resolved → state.address is set, advance to next phase
 *   awaiting → state.addressChoices is set, present picker, wait for user
 *   failed   → set phase=failed, send reply
 */
type EnsureAddressResult =
  | { kind: 'resolved' }
  | { kind: 'awaiting'; reply: string }
  | { kind: 'failed'; reply: string };

const MAX_ADDRESS_CHOICES = 6;

async function ensureAddress(
  userId: string,
  state: OrderState,
  provider: GroceryProvider,
): Promise<EnsureAddressResult> {
  // Already resolved on this turn / a previous turn.
  if (state.address?.id) return { kind: 'resolved' };

  const addresses = await provider.listAddresses(userId);
  if (addresses.length === 0) {
    recordError(state, 'ensure_address', 'no_address', 'no saved addresses');
    return {
      kind: 'failed',
      reply: 'You have no saved delivery address on Zepto. Open the Zepto app, add one, then come back 🙏',
    };
  }

  // Path 1: user has a saved default — use it silently.
  const userRow = await db.query.users.findFirst({
    where: eq(users.id, userId),
    columns: { defaultZeptoAddressId: true },
  });
  const savedId = userRow?.defaultZeptoAddressId;
  if (savedId) {
    const match = addresses.find((a) => a.id === savedId);
    if (match) {
      await provider.selectAddress(userId, match.id);
      state.address = { id: match.id, label: match.label };
      trace(state, 'ensure_address', `using saved default ${match.id}`);
      return { kind: 'resolved' };
    }
    // Saved ID no longer exists on Zepto — clear it and fall through.
    await db.update(users).set({ defaultZeptoAddressId: null }).where(eq(users.id, userId));
    trace(state, 'ensure_address', 'saved default not found in Zepto list; cleared');
  }

  // Path 2: only one saved address — auto-pick it AND save as default.
  if (addresses.length === 1) {
    const only = addresses[0]!;
    await provider.selectAddress(userId, only.id);
    state.address = { id: only.id, label: only.label };
    await db
      .update(users)
      .set({ defaultZeptoAddressId: only.id })
      .where(eq(users.id, userId));
    trace(state, 'ensure_address', `auto-saved single address as default`);
    return { kind: 'resolved' };
  }

  // Path 3: multiple addresses, no saved default — present picker.
  const choices = addresses.slice(0, MAX_ADDRESS_CHOICES);
  state.addressChoices = choices.map((a) => ({ id: a.id, label: a.label }));
  trace(state, 'await_address_choice', `presenting ${choices.length} options`);
  return {
    kind: 'awaiting',
    reply: presentAddressChoicesReply(choices, addresses.length),
  };
}

function presentAddressChoicesReply(
  shown: AddressState[],
  totalAvailable: number,
): string {
  const lines = shown.map((a, i) => `${i + 1}. ${escapeHtml(a.label)}`);
  const more =
    totalAvailable > shown.length
      ? `\n\n(${totalAvailable - shown.length} more on Zepto — pick one of these or open the Zepto app to manage)`
      : '';
  return [
    `<b>Where should I deliver?</b>`,
    '',
    lines.join('\n'),
    '',
    `Reply with the number. I'll remember it for next time.${more}`,
  ].join('\n');
}

function parseAddressChoice(text: string, optionCount: number): number | null {
  const m = text.trim().match(/^(?:option\s*)?(\d+)\b/i);
  if (!m) return null;
  const n = Number(m[1]);
  if (n >= 1 && n <= optionCount) return n;
  return null;
}

async function persistDefaultAddress(userId: string, addressId: string): Promise<void> {
  await db
    .update(users)
    .set({ defaultZeptoAddressId: addressId, updatedAt: new Date() })
    .where(eq(users.id, userId));
}

function pickBestProduct(group: SearchGroup): ProductOption | null {
  for (const p of group.products) {
    if (p.available && p.productVariantId && p.storeProductId) return p;
  }
  return group.products[0] ?? null;
}

async function buildCartAndPreview(
  userId: string,
  state: OrderState,
  provider: GroceryProvider,
): Promise<{ ok: boolean; reply?: string }> {
  if (state.requests.length === 0) {
    recordError(state, 'preparing_preview', 'no_queries', 'no queries to search');
    return { ok: false, reply: 'What would you like to order?' };
  }

  // Search by query, then zip back with the user-stated quantity by index.
  const queries = state.requests.map((r) => r.query);
  const groups = await provider.searchMany(userId, queries);
  const cart: CartLineState[] = [];
  const unmatched: string[] = [];
  groups.forEach((g, idx) => {
    const requested = state.requests[idx]?.quantity ?? 1;
    const top = pickBestProduct(g);
    if (!top) {
      unmatched.push(g.query);
      return;
    }
    cart.push({
      query: g.query,
      productVariantId: top.productVariantId,
      storeProductId: top.storeProductId,
      name: top.name,
      packSize: top.packSize,
      pricePaise: top.pricePaise,
      quantity: requested,
    });
  });
  state.cart = cart;
  state.unmatchedQueries = unmatched;
  trace(state, 'preparing_preview', `cart=${cart.length} unmatched=${unmatched.length}`);

  if (cart.length === 0) {
    recordError(state, 'preparing_preview', 'all_unmatched', `nothing matched: ${unmatched.join(', ')}`);
    return {
      ok: false,
      reply: `Couldn't find any of: <b>${unmatched.map(escapeHtml).join(', ')}</b>. Try a more specific name or check spelling.`,
    };
  }

  // Stage cart on the provider.
  const cartResult = await provider.upsertCart(
    userId,
    cart.map((l) => ({
      productVariantId: l.productVariantId,
      storeProductId: l.storeProductId,
      quantity: l.quantity,
      name: l.name,
      pricePaise: l.pricePaise,
    })),
    { replace: true },
  );

  // Live preview with fees.
  let preview: OrderPreview;
  try {
    preview = await provider.previewOrder(userId, {
      addressId: state.address!.id,
      paymentMethod: 'cod',
    });
  } catch (err) {
    if (err instanceof GroceryProviderError) {
      recordError(state, 'preparing_preview', 'preview_failed', err.message);
      return { ok: false, reply: `Couldn't price the cart: ${escapeHtml(err.message)}` };
    }
    throw err;
  }

  state.preview = {
    cartKey: cartResult.cartKey ?? preview.cartKey,
    subtotalPaise: preview.subtotalPaise,
    deliveryFeePaise: preview.deliveryFeePaise,
    handlingFeePaise: preview.handlingFeePaise,
    totalPaise: preview.totalPaise,
    etaMinutes: preview.etaMinutes,
  };
  trace(state, 'preparing_preview', `total=${preview.totalPaise}`);
  return { ok: true };
}

async function placeOrder(
  userId: string,
  state: OrderState,
  provider: GroceryProvider,
): Promise<{ ok: boolean; reply?: string }> {
  if (!state.address?.id) {
    recordError(state, 'placing', 'no_address', 'address missing at place time');
    return { ok: false, reply: "Lost track of your delivery address — start over please." };
  }
  try {
    const placed = await provider.placeOrder(userId, {
      cartKey: state.preview?.cartKey,
      addressId: state.address.id,
      paymentMethod: 'cod',
    });
    state.order = { id: placed.orderId, placedAt: new Date().toISOString() };
    trace(state, 'placing', `placed id=${placed.orderId}`);
    return { ok: true };
  } catch (err) {
    if (err instanceof GroceryProviderError) {
      recordError(state, 'placing', 'place_failed', err.message);
      return { ok: false, reply: `Order placement failed: ${escapeHtml(err.message)}` };
    }
    throw err;
  }
}

// ─────────────────────────────────────────────────────────────────────────
// Orchestrator
// ─────────────────────────────────────────────────────────────────────────

export async function runOrderTurn(input: OrderTurnInput): Promise<WorkflowReply> {
  const { userId, message } = input;

  // Hard cancel at any point.
  if (parseConfirm(message) === 'no' && message.trim().length <= 15) {
    const existing = await load(userId);
    if (existing) {
      existing.state.phase = 'cancelled';
      trace(existing.state, 'cancelled', 'user cancelled');
      await save(userId, existing.state, existing.task);
    }
    return { text: 'Cancelled. No order placed 👍', finished: true };
  }

  const loaded = await load(userId);
  const restart =
    !loaded ||
    loaded.state.phase === 'completed' ||
    loaded.state.phase === 'cancelled' ||
    loaded.state.phase === 'failed';

  let state: OrderState;
  let existingTask: AgentTask | undefined;
  if (restart) {
    state = blank();
    state.requests = input.orderItems ?? [];
    if (state.requests.length === 0) {
      // Classifier didn't extract anything (rare — e.g. it labeled this as
      // 'order' but couldn't pull a product). Bail out cleanly.
      return {
        text: 'What would you like to order? Tell me the items and quantities.',
        finished: true,
      };
    }
    state.phase = 'ensure_address';
    trace(state, 'ensure_address', `start requests=${JSON.stringify(state.requests)}`);
  } else {
    state = loaded!.state;
    existingTask = loaded!.task;
  }

  let provider: GroceryProvider;
  try {
    provider = await getGroceryProvider(userId);
  } catch (err) {
    if (err instanceof GroceryProviderNotConnectedError) {
      return {
        text: "You haven't connected Zepto yet. Visit aajkyakhaun.com/app to connect, then try again.",
        finished: true,
      };
    }
    throw err;
  }

  try {
    if (state.phase === 'ensure_address') {
      const r = await ensureAddress(userId, state, provider);
      if (r.kind === 'failed') {
        state.phase = 'failed';
        await save(userId, state, existingTask);
        return { text: r.reply, finished: true };
      }
      if (r.kind === 'awaiting') {
        state.phase = 'await_address_choice';
        await save(userId, state, existingTask);
        return { text: r.reply };
      }
      state.phase = 'preparing_preview';
    }

    if (state.phase === 'await_address_choice') {
      const choices = state.addressChoices ?? [];
      const pick = parseAddressChoice(message, choices.length);
      if (!pick) {
        return {
          text: `Reply with the number (1-${choices.length}) of the address to deliver to.`,
        };
      }
      const chosen = choices[pick - 1]!;
      await provider.selectAddress(userId, chosen.id);
      state.address = chosen;
      state.addressChoices = undefined;
      await persistDefaultAddress(userId, chosen.id);
      trace(state, 'await_address_choice', `picked ${chosen.id}; saved as default`);
      state.phase = 'preparing_preview';
      // Fall through to preparing_preview on the same turn — better UX than
      // making the user wait another round-trip just to see the cart.
    }

    if (state.phase === 'preparing_preview') {
      const r = await buildCartAndPreview(userId, state, provider);
      if (!r.ok) {
        state.phase = 'failed';
        await save(userId, state, existingTask);
        return { text: r.reply ?? 'Could not prepare preview.', finished: true };
      }
      state.phase = 'await_confirm';
      await save(userId, state, existingTask);
      return { text: presentPreviewReply(state) };
    }

    if (state.phase === 'await_confirm') {
      const decision = parseConfirm(message);
      if (decision === 'no') {
        state.phase = 'cancelled';
        trace(state, 'cancelled', 'user declined');
        await save(userId, state, existingTask);
        return { text: 'Cancelled. No order placed 👍', finished: true };
      }
      if (decision === 'yes') {
        state.phase = 'placing';
        const r = await placeOrder(userId, state, provider);
        if (!r.ok) {
          state.phase = 'failed';
          await save(userId, state, existingTask);
          return { text: r.reply ?? 'Order placement failed.', finished: true };
        }
        state.phase = 'completed';
        await save(userId, state, existingTask);
        return { text: placedReply(state), finished: true };
      }

      // Neither yes nor no. If the classifier pulled new items, treat this
      // as an "add to cart" request — append, rebuild the preview, ask again.
      if (input.orderItems && input.orderItems.length > 0) {
        state.requests = [...state.requests, ...input.orderItems];
        trace(
          state,
          'preparing_preview',
          `mid-confirm add: +${input.orderItems.length} items`,
        );
        const r = await buildCartAndPreview(userId, state, provider);
        if (!r.ok) {
          state.phase = 'failed';
          await save(userId, state, existingTask);
          return { text: r.reply ?? 'Could not rebuild preview.', finished: true };
        }
        // Stay in await_confirm — show the new preview and wait again.
        await save(userId, state, existingTask);
        return { text: presentPreviewReply(state) };
      }

      return {
        text:
          'Reply <b>yes</b> to place, <b>no</b> to cancel, or tell me what else to add ' +
          '(e.g. <i>add 1 hakka noodles</i>). Removing items isn\'t wired yet — say no and re-order to drop something.',
      };
    }

    log.warn(`fell through phase=${state.phase}`, { userId });
    return { text: "Let me know what you'd like to order." };
  } catch (err) {
    log.error('unhandled order workflow error', err);
    state.phase = 'failed';
    recordError(state, state.phase, 'unhandled', err instanceof Error ? err.message : String(err));
    try { await save(userId, state, existingTask); } catch { /* ignore */ }
    return {
      text: 'Something went sideways while preparing the order. Try again in a minute 🙏',
      finished: true,
    };
  }
}

/** Diagnostic export. */
export async function getActiveOrderState(userId: string): Promise<OrderState | null> {
  const loaded = await load(userId);
  return loaded?.state ?? null;
}
