/**
 * Multi-item grocery order workflow.
 *
 * State machine:
 *   new → ensure_address → preparing_preview → await_confirm
 *     → placing → completed
 *                 ↓
 *               failed / cancelled
 *
 * Single confirmation: cart + fees + total are presented together. The
 * user reviews everything in one message and replies "yes" / "no". The
 * preview is generated by provider.previewOrder({ confirmOrder: false })
 * so fees come from the live cart, not estimates.
 *
 * One quantity-1 line per query in the user's request. Mid-cart edits
 * (remove, change, requantify) are not implemented in v1 — replying with
 * a new query list re-starts the flow.
 *
 * State persists in agent_tasks(type='order') with kind='order_v3' to
 * avoid colliding with the legacy zepto_order_v2 state shape.
 */

import { and, desc, eq, gt, inArray } from 'drizzle-orm';
import { db } from '../../config/database.js';
import { agentTasks, users, type AgentTask } from '../../db/schema.js';
import {
  classifyOrderAction,
  classifyProductChoice,
  disambiguateSearchResults,
  type CartLineSummary,
} from '../../agent/intent.js';
import {
  type GroceryProvider,
  GroceryProviderError,
  GroceryProviderNotConnectedError,
  type OrderPreview,
  type ProductOption,
} from '../../providers/grocery/index.js';
import { getGroceryProvider } from '../../providers/grocery/index.js';
import { escapeHtml } from '../../utils/html.js';
import { createLogger } from '../../utils/logger.js';

const log = createLogger('order-workflow');

// ─────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────

export type Phase =
  | 'new'
  | 'ensure_address'
  | 'await_address_choice'
  | 'preparing_preview'
  | 'await_line_choice'
  | 'await_confirm'
  | 'placing'
  | 'completed'
  | 'failed'
  | 'cancelled';

export interface CartLineState {
  /** Index into state.requests this line was built from. Used for line-targeted edits. */
  requestIndex: number;
  query: string;
  productVariantId: string;
  storeProductId: string;
  name: string;
  packSize: string;
  pricePaise: number;
  quantity: number;
}

export interface AddressState {
  id: string;
  label: string;
}

export interface PreviewState {
  cartKey?: string;
  subtotalPaise: number;
  deliveryFeePaise: number;
  handlingFeePaise: number;
  totalPaise: number;
  etaMinutes?: number;
  deliverable: boolean;
}

export interface PhaseTrace { phase: Phase; action: string; at: string; }
export interface PhaseError { phase: Phase; code: string; message: string; at: string; }

export interface ResolvedProduct {
  productVariantId: string;
  storeProductId: string;
  cartProductId: string | null;
  name: string;
  packSize: string;
  pricePaise: number;
}

export interface PendingChoice {
  /** Index into state.requests this choice resolves. */
  requestIndex: number;
  query: string;
  candidates: ResolvedProduct[];
}

export interface OrderState {
  kind: 'order_v3';
  phase: Phase;
  /** Original queries with requested quantities, in user-stated order. */
  requests: OrderItemRequest[];
  /** Pending address candidates while we wait for the user's pick. */
  addressChoices?: AddressState[];
  /**
   * Confirmed product per requestIndex — accumulates from confident matches
   * and from the user's pick during await_line_choice. Cleared on rebuild.
   */
  resolvedProducts?: Record<number, ResolvedProduct>;
  /** Queue of ambiguous queries waiting on the user. Front is the active one. */
  pendingChoices?: PendingChoice[];
  /**
   * When the user picks an address in await_address_choice, persist it as
   * users.default_zepto_address_id only if this flag is true. First-time
   * picks set it true; one-time overrides (change_address mid-flow,
   * serviceability fallbacks) set it false so the permanent default isn't
   * clobbered by a transient choice.
   */
  savePickAsDefault?: boolean;
  unmatchedQueries: string[];
  address?: AddressState;
  cart?: CartLineState[];
  preview?: PreviewState;
  order?: { id?: string; placedAt: string };
  errors: PhaseError[];
  trace: PhaseTrace[];
  updatedAt: string;
}

export interface OrderItemRequest {
  query: string;
  quantity: number;
}

export interface OrderTurnInput {
  userId: string;
  message: string;
  /**
   * Structured items from the intent classifier — one entry per distinct
   * product the user wants, with quantity. If undefined or empty, this turn
   * is treated as a confirmation / continuation of an existing workflow.
   */
  orderItems?: OrderItemRequest[];
}

export interface WorkflowReply {
  text: string;
  finished?: boolean;
}

// ─────────────────────────────────────────────────────────────────────────
// Persistence
// ─────────────────────────────────────────────────────────────────────────

const WORKFLOW_TTL_MS = 30 * 60 * 1000;
const ACTIVE_STATUSES = ['active', 'waiting_user'] as const;

function blank(): OrderState {
  return {
    kind: 'order_v3',
    phase: 'new',
    requests: [],
    unmatchedQueries: [],
    errors: [],
    trace: [],
    updatedAt: new Date().toISOString(),
  };
}

function isOrderState(s: unknown): s is OrderState {
  return typeof s === 'object' && s !== null
    && (s as { kind?: unknown }).kind === 'order_v3';
}

async function load(userId: string): Promise<{ task: AgentTask; state: OrderState } | null> {
  const [task] = await db
    .select()
    .from(agentTasks)
    .where(
      and(
        eq(agentTasks.userId, userId),
        eq(agentTasks.type, 'order'),
        inArray(agentTasks.status, [...ACTIVE_STATUSES]),
        gt(agentTasks.expiresAt, new Date()),
      ),
    )
    .orderBy(desc(agentTasks.updatedAt))
    .limit(1);
  if (!task || !isOrderState(task.state)) return null;
  return { task, state: task.state };
}

async function save(userId: string, state: OrderState, existing?: AgentTask): Promise<void> {
  state.updatedAt = new Date().toISOString();
  const status =
    state.phase === 'completed' ? 'completed'
      : state.phase === 'cancelled' ? 'cancelled'
      : state.phase === 'failed' ? 'failed'
      : 'waiting_user';
  const expiresAt = status === 'waiting_user' ? new Date(Date.now() + WORKFLOW_TTL_MS) : null;

  if (existing) {
    await db
      .update(agentTasks)
      .set({
        status,
        state,
        expiresAt: expiresAt ?? existing.expiresAt,
        updatedAt: new Date(),
      })
      .where(eq(agentTasks.id, existing.id));
    return;
  }
  await db.insert(agentTasks).values({
    userId,
    type: 'order',
    status,
    state,
    expiresAt: expiresAt ?? new Date(Date.now() + WORKFLOW_TTL_MS),
  });
}

function trace(state: OrderState, phase: Phase, action: string): void {
  state.trace.push({ phase, action, at: new Date().toISOString() });
  if (state.trace.length > 40) state.trace.splice(0, state.trace.length - 40);
}
function recordError(state: OrderState, phase: Phase, code: string, message: string): void {
  state.errors.push({ phase, code, message: message.slice(0, 500), at: new Date().toISOString() });
  log.warn(`[phase=${phase}] ${code}: ${message}`);
}

// ─────────────────────────────────────────────────────────────────────────
// Cart helpers
// ─────────────────────────────────────────────────────────────────────────

/**
 * Translate provider error strings into something a user can act on.
 * Substring matches only (not interpretation) — Zepto's MCP returns
 * stable error tokens like STORE_CLOSED, NOT_SERVICEABLE, etc. that we
 * can recognize without an LLM hop.
 */
function friendlyProviderError(rawMessage: string, fallback: string): string {
  const m = rawMessage.toLowerCase();
  if (m.includes('store_closed') || m.includes('store closed')) {
    return (
      'The Zepto store serving your address is closed right now. ' +
      'Try again later, or pick a different address.'
    );
  }
  if (
    m.includes('not deliverable') ||
    m.includes('not_deliverable') ||
    m.includes('unserviceable') ||
    m.includes('not_serviceable')
  ) {
    return (
      'Zepto can\'t deliver to your address right now. ' +
      'Try a different saved address.'
    );
  }
  if (
    m.includes('out of stock') ||
    m.includes('out_of_stock') ||
    m.includes('not_available') ||
    m.includes('unavailable')
  ) {
    return 'Some items just went out of stock on Zepto. Try again or swap them.';
  }
  if (m.includes('rate limit') || m.includes('too many requests') || m.includes('429')) {
    return 'Zepto is rate-limiting us — try again in a minute 🙏';
  }
  if (m.includes('timeout') || m.includes('timed out') || m.includes('econnreset')) {
    return 'Zepto didn\'t respond in time. Try again in a moment.';
  }
  if (m.includes('not_connected') || m.includes('not connected')) {
    return 'Zepto session expired. Reconnect at aajkyakhaun.com/app.';
  }
  return fallback;
}

/**
 * True if the provider's error message indicates an address-related
 * failure that the user can resolve by picking a different address.
 */
function isServiceabilityError(message: string): boolean {
  const m = message.toLowerCase();
  return (
    m.includes('store_closed') ||
    m.includes('store closed') ||
    m.includes('not deliverable') ||
    m.includes('not_deliverable') ||
    m.includes('unserviceable') ||
    m.includes('not_serviceable')
  );
}

/**
 * Pivot a stuck order into the address picker without losing the cart.
 * Used both when:
 *   - The user explicitly says "deliver elsewhere" (change_address action)
 *   - A preview/place fails with a serviceability error
 *
 * The chosen address is treated as a one-time override for THIS order:
 * we never overwrite users.default_zepto_address_id from this path.
 */
async function offerAddressChange(
  userId: string,
  state: OrderState,
  provider: GroceryProvider,
  existingTask: AgentTask | undefined,
  prefaceReply: string,
): Promise<WorkflowReply> {
  const addresses = await provider.listAddresses(userId);
  if (addresses.length <= 1) {
    state.phase = 'failed';
    await save(userId, state, existingTask);
    return {
      text:
        prefaceReply +
        '\n\n(No alternative addresses on Zepto — open the Zepto app to add one, then come back.)',
      finished: true,
    };
  }
  const choices = addresses.slice(0, MAX_ADDRESS_CHOICES);
  state.addressChoices = choices.map((a) => ({ id: a.id, label: a.label }));
  state.savePickAsDefault = false; // one-time override, not a default change
  state.address = undefined;
  state.phase = 'await_address_choice';
  trace(state, 'await_address_choice', `offering change among ${choices.length}`);
  await save(userId, state, existingTask);
  return {
    text:
      (prefaceReply ? prefaceReply + '\n\n' : '') +
      presentAddressChoicesReply(choices, addresses.length),
  };
}

function cartSummary(state: OrderState): CartLineSummary[] {
  return (state.cart ?? []).map((l, i) => ({
    index: i + 1,
    name: l.name,
    quantity: l.quantity,
    pricePaise: l.pricePaise,
  }));
}

/**
 * Translate user-visible 1-based cart line numbers (from the LLM action
 * classifier) into indices in state.requests — which is the source of truth
 * the rebuild iterates. Lines without a backing cart entry (out of range,
 * already-unmatched) get silently dropped.
 */
function mapTargetLinesToRequestIndices(state: OrderState, targetLines: number[]): number[] {
  const out: number[] = [];
  for (const line of targetLines) {
    const cartLine = state.cart?.[line - 1];
    if (cartLine && !out.includes(cartLine.requestIndex)) {
      out.push(cartLine.requestIndex);
    }
  }
  return out;
}

/**
 * Rebuild the cart + live preview after a state.requests mutation. If any
 * line is ambiguous, transitions to await_line_choice and presents the
 * picker. Otherwise stays in await_confirm and shows the priced preview.
 */
async function rebuildAndPresent(
  userId: string,
  state: OrderState,
  provider: GroceryProvider,
  existingTask: AgentTask | undefined,
): Promise<WorkflowReply> {
  const r = await buildCartAndPreview(userId, state, provider);
  if (!r.ok) {
    if (r.serviceability) {
      // Cart is fine; the address isn't. Pivot to the picker without
      // killing the workflow.
      return offerAddressChange(
        userId,
        state,
        provider,
        existingTask,
        r.reply ?? 'That address isn\'t serviceable right now.',
      );
    }
    state.phase = 'failed';
    await save(userId, state, existingTask);
    return { text: r.reply ?? 'Could not rebuild preview.', finished: true };
  }
  if (r.needsChoice) {
    state.phase = 'await_line_choice';
    await save(userId, state, existingTask);
    return { text: presentLineChoiceReply(state) };
  }
  if (state.preview && !state.preview.deliverable) {
    return offerAddressChange(
      userId,
      state,
      provider,
      existingTask,
      presentUnserviceableReply(state),
    );
  }
  state.phase = 'await_confirm';
  await save(userId, state, existingTask);
  return { text: presentPreviewReply(state) };
}

function presentLineChoiceReply(state: OrderState): string {
  const pending = state.pendingChoices?.[0];
  if (!pending) return 'No pending choices.';
  const lines = pending.candidates.map((c, i) => {
    const meta: string[] = [];
    if (c.packSize) meta.push(escapeHtml(c.packSize));
    if (c.pricePaise) meta.push(`<b>${rupees(c.pricePaise)}</b>`);
    return `${i + 1}. ${escapeHtml(c.name)}${meta.length ? ' · ' + meta.join(' · ') : ''}`;
  });
  const remaining = (state.pendingChoices?.length ?? 1) - 1;
  const tail = remaining > 0 ? `\n\n(${remaining} more line${remaining === 1 ? '' : 's'} after this)` : '';
  return [
    `Multiple matches for <b>${escapeHtml(pending.query)}</b>:`,
    '',
    lines.join('\n'),
    '',
    `Reply with the number to pick, or <i>skip</i> to drop this item.${tail}`,
  ].join('\n');
}


// ─────────────────────────────────────────────────────────────────────────
// Reply formatters
// ─────────────────────────────────────────────────────────────────────────

function rupees(paise: number): string {
  if (paise === 0) return '₹0';
  return `₹${(paise / 100).toFixed(paise % 100 === 0 ? 0 : 2)}`;
}

function presentUnserviceableReply(state: OrderState): string {
  const addr = state.address?.label
    ? ` to <b>${escapeHtml(state.address.label)}</b>`
    : '';
  return [
    `Zepto says it can't deliver${addr} right now (store unserviceable or out of hours).`,
    '',
    `Try a different address — say <i>change address</i> or open the Zepto app to pick one that's serviceable.`,
  ].join('\n');
}

function presentPreviewReply(state: OrderState): string {
  const cart = state.cart ?? [];
  const pre = state.preview;
  if (!pre) return 'Preparing preview…';

  const lines = cart.map((l, i) => {
    const qty = l.quantity > 1 ? ` × ${l.quantity}` : '';
    const sub = `${escapeHtml(l.name)}${qty}`;
    const meta: string[] = [];
    if (l.packSize) meta.push(escapeHtml(l.packSize));
    if (l.pricePaise > 0) meta.push(`<b>${rupees(l.pricePaise * l.quantity)}</b>`);
    return `${i + 1}. ${sub}${meta.length ? ' · ' + meta.join(' · ') : ''}`;
  });

  const addr = state.address?.label ? ` to ${escapeHtml(state.address.label)}` : '';
  const eta = pre.etaMinutes ? `\n⏱ ETA ~${pre.etaMinutes} min` : '';
  const unmatched = state.unmatchedQueries.length
    ? `\n\n⚠️ Couldn't find: ${state.unmatchedQueries.map(escapeHtml).join(', ')}`
    : '';

  return [
    `<b>Cart preview</b>${addr}:`,
    '',
    lines.join('\n'),
    '',
    `Subtotal: <b>${rupees(pre.subtotalPaise)}</b>`,
    `Delivery: ${rupees(pre.deliveryFeePaise)}`,
    `Handling: ${rupees(pre.handlingFeePaise)}`,
    `<b>Total: ${rupees(pre.totalPaise)}</b> · COD${eta}${unmatched}`,
    '',
    'Reply <b>yes</b> to place, <b>no</b> to cancel.',
  ].join('\n');
}

function placedReply(state: OrderState): string {
  const total = state.preview?.totalPaise;
  const id = state.order?.id;
  const idLine = id ? `\nOrder id: <code>${escapeHtml(id)}</code>` : '';
  const totalLine = total ? ` for <b>${rupees(total)}</b>` : '';
  return `✅ Order placed${totalLine} on COD.${idLine}\n\nI'll update your pantry once it arrives 🍽️`;
}

// ─────────────────────────────────────────────────────────────────────────
// Phases
// ─────────────────────────────────────────────────────────────────────────

/**
 * Result discriminator for ensureAddress:
 *   resolved → state.address is set, advance to next phase
 *   awaiting → state.addressChoices is set, present picker, wait for user
 *   failed   → set phase=failed, send reply
 */
type EnsureAddressResult =
  | { kind: 'resolved' }
  | { kind: 'awaiting'; reply: string }
  | { kind: 'failed'; reply: string };

const MAX_ADDRESS_CHOICES = 6;

async function ensureAddress(
  userId: string,
  state: OrderState,
  provider: GroceryProvider,
): Promise<EnsureAddressResult> {
  // Already resolved on this turn / a previous turn.
  if (state.address?.id) return { kind: 'resolved' };

  const addresses = await provider.listAddresses(userId);
  if (addresses.length === 0) {
    recordError(state, 'ensure_address', 'no_address', 'no saved addresses');
    return {
      kind: 'failed',
      reply: 'You have no saved delivery address on Zepto. Open the Zepto app, add one, then come back 🙏',
    };
  }

  // Path 1: user has a saved default — use it silently.
  const userRow = await db.query.users.findFirst({
    where: eq(users.id, userId),
    columns: { defaultZeptoAddressId: true },
  });
  const savedId = userRow?.defaultZeptoAddressId;
  if (savedId) {
    const match = addresses.find((a) => a.id === savedId);
    if (match) {
      await provider.selectAddress(userId, match.id);
      state.address = { id: match.id, label: match.label };
      trace(state, 'ensure_address', `using saved default ${match.id}`);
      return { kind: 'resolved' };
    }
    // Saved ID no longer exists on Zepto — clear it and fall through.
    await db.update(users).set({ defaultZeptoAddressId: null }).where(eq(users.id, userId));
    trace(state, 'ensure_address', 'saved default not found in Zepto list; cleared');
  }

  // Path 2: only one saved address — auto-pick it AND save as default.
  if (addresses.length === 1) {
    const only = addresses[0]!;
    await provider.selectAddress(userId, only.id);
    state.address = { id: only.id, label: only.label };
    await db
      .update(users)
      .set({ defaultZeptoAddressId: only.id })
      .where(eq(users.id, userId));
    trace(state, 'ensure_address', `auto-saved single address as default`);
    return { kind: 'resolved' };
  }

  // Path 3: multiple addresses, no saved default — present picker. This is
  // a first-time pick, so we WILL persist the choice as the user's default.
  const choices = addresses.slice(0, MAX_ADDRESS_CHOICES);
  state.addressChoices = choices.map((a) => ({ id: a.id, label: a.label }));
  state.savePickAsDefault = true;
  trace(state, 'await_address_choice', `presenting ${choices.length} options (first time)`);
  return {
    kind: 'awaiting',
    reply: presentAddressChoicesReply(choices, addresses.length),
  };
}

function presentAddressChoicesReply(
  shown: AddressState[],
  totalAvailable: number,
): string {
  const lines = shown.map((a, i) => `${i + 1}. ${escapeHtml(a.label)}`);
  const more =
    totalAvailable > shown.length
      ? `\n\n(${totalAvailable - shown.length} more on Zepto — pick one of these or open the Zepto app to manage)`
      : '';
  return [
    `<b>Where should I deliver?</b>`,
    '',
    lines.join('\n'),
    '',
    `Reply with the number. I'll remember it for next time.${more}`,
  ].join('\n');
}

function parseAddressChoice(text: string, optionCount: number): number | null {
  const n = parseInt(text.trim(), 10);
  return Number.isInteger(n) && n >= 1 && n <= optionCount ? n : null;
}

async function persistDefaultAddress(userId: string, addressId: string): Promise<void> {
  await db
    .update(users)
    .set({ defaultZeptoAddressId: addressId, updatedAt: new Date() })
    .where(eq(users.id, userId));
}

/**
 * Maximum candidates we'll show the user when disambiguating one line.
 * Anything more is overwhelming on a chat surface.
 */
const MAX_CHOICE_CANDIDATES = 3;

function toResolved(p: ProductOption): ResolvedProduct {
  return {
    productVariantId: p.productVariantId,
    storeProductId: p.storeProductId,
    cartProductId: p.cartProductId,
    name: p.name,
    packSize: p.packSize,
    pricePaise: p.pricePaise,
  };
}

/**
 * Stage 1 of cart construction. Search Zepto for every request, then run
 * the LLM disambiguator per group. Confident matches accumulate in
 * state.resolvedProducts. Ambiguous ones queue up in state.pendingChoices
 * for the await_line_choice phase to resolve one at a time.
 */
async function searchAndDisambiguate(
  userId: string,
  state: OrderState,
  provider: GroceryProvider,
): Promise<{ ok: boolean; reply?: string }> {
  if (state.requests.length === 0) {
    recordError(state, 'preparing_preview', 'no_queries', 'no queries to search');
    return { ok: false, reply: 'What would you like to order?' };
  }

  // Reset derived state for a fresh build.
  state.resolvedProducts = {};
  state.pendingChoices = [];
  state.unmatchedQueries = [];
  state.cart = undefined;
  state.preview = undefined;

  const queries = state.requests.map((r) => r.query);
  const groups = await provider.searchMany(userId, queries);

  for (let idx = 0; idx < groups.length; idx++) {
    const g = groups[idx]!;
    const orderable = g.products.filter(
      (p) => p.productVariantId && p.storeProductId,
    );
    if (orderable.length === 0) {
      state.unmatchedQueries.push(g.query);
      continue;
    }

    // Deduplicate by productVariantId so the disambiguator doesn't see the
    // same SKU listed twice (Zepto often returns two storeProductId rows
    // for the same variant when multiple slots stock it).
    const seen = new Set<string>();
    const unique: ProductOption[] = [];
    for (const p of orderable) {
      if (!seen.has(p.productVariantId)) {
        seen.add(p.productVariantId);
        unique.push(p);
      }
    }

    const decision = await disambiguateSearchResults(
      g.query,
      unique.map((p) => ({
        name: p.name,
        packSize: p.packSize,
        pricePaise: p.pricePaise,
      })),
    );

    if (decision.kind === 'no_match') {
      state.unmatchedQueries.push(g.query);
      continue;
    }
    if (decision.kind === 'confident') {
      const pick = unique[decision.pickIndex] ?? unique[0]!;
      state.resolvedProducts[idx] = toResolved(pick);
      continue;
    }
    // ambiguous → queue for user choice (top N indices, capped)
    const candidates = decision.showIndices
      .slice(0, MAX_CHOICE_CANDIDATES)
      .map((i) => unique[i])
      .filter((p): p is ProductOption => p !== undefined)
      .map(toResolved);
    if (candidates.length === 0) {
      // shouldn't happen, but fall back to top-1 confident.
      state.resolvedProducts[idx] = toResolved(unique[0]!);
      continue;
    }
    state.pendingChoices.push({
      requestIndex: idx,
      query: g.query,
      candidates,
    });
  }

  trace(
    state,
    'preparing_preview',
    `resolved=${Object.keys(state.resolvedProducts).length} ` +
      `pending=${state.pendingChoices.length} unmatched=${state.unmatchedQueries.length}`,
  );

  // If nothing matched at all, bail.
  const totalMatched =
    Object.keys(state.resolvedProducts).length + state.pendingChoices.length;
  if (totalMatched === 0) {
    recordError(
      state,
      'preparing_preview',
      'all_unmatched',
      `nothing matched: ${state.unmatchedQueries.join(', ')}`,
    );
    return {
      ok: false,
      reply: `Couldn't find any of: <b>${state.unmatchedQueries
        .map(escapeHtml)
        .join(', ')}</b>. Try more specific names.`,
    };
  }
  return { ok: true };
}

/**
 * Stage 2 of cart construction. All requests resolved (no pendingChoices).
 * Build CartLineState[] from resolvedProducts, push to provider, fetch
 * priced preview.
 */
async function assemblePreview(
  userId: string,
  state: OrderState,
  provider: GroceryProvider,
): Promise<{ ok: boolean; reply?: string; serviceability?: boolean }> {
  const resolved = state.resolvedProducts ?? {};
  const cart: CartLineState[] = [];
  state.requests.forEach((req, idx) => {
    const r = resolved[idx];
    if (!r) return; // unmatched / skipped
    cart.push({
      requestIndex: idx,
      query: req.query,
      productVariantId: r.productVariantId,
      storeProductId: r.storeProductId,
      name: r.name,
      packSize: r.packSize,
      pricePaise: r.pricePaise,
      quantity: req.quantity,
    });
  });
  state.cart = cart;

  if (cart.length === 0) {
    recordError(state, 'preparing_preview', 'empty_cart', 'no resolved lines');
    return {
      ok: false,
      reply: 'Cart ended up empty. Tell me what to order again?',
    };
  }

  const cartResult = await provider.upsertCart(
    userId,
    cart.map((l) => ({
      productVariantId: l.productVariantId,
      storeProductId: l.storeProductId,
      quantity: l.quantity,
      name: l.name,
      pricePaise: l.pricePaise,
    })),
    { replace: true },
  );

  let preview: OrderPreview;
  try {
    preview = await provider.previewOrder(userId, {
      addressId: state.address!.id,
      paymentMethod: 'cod',
    });
  } catch (err) {
    if (err instanceof GroceryProviderError) {
      recordError(state, 'preparing_preview', 'preview_failed', err.message);
      return {
        ok: false,
        serviceability: isServiceabilityError(err.message),
        reply: friendlyProviderError(
          err.message,
          'Couldn\'t price the cart right now. Try again in a moment 🙏',
        ),
      };
    }
    throw err;
  }

  state.preview = {
    cartKey: cartResult.cartKey ?? preview.cartKey,
    subtotalPaise: preview.subtotalPaise,
    deliveryFeePaise: preview.deliveryFeePaise,
    handlingFeePaise: preview.handlingFeePaise,
    totalPaise: preview.totalPaise,
    etaMinutes: preview.etaMinutes,
    deliverable: preview.deliverable,
  };
  trace(state, 'preparing_preview', `total=${preview.totalPaise} deliverable=${preview.deliverable}`);
  return { ok: true };
}

/**
 * Replaces the legacy buildCartAndPreview entry point. Tries to fully
 * resolve all lines and price the cart. If any line is ambiguous, returns
 * { needsChoice: true } so the orchestrator can flip to await_line_choice.
 */
async function buildCartAndPreview(
  userId: string,
  state: OrderState,
  provider: GroceryProvider,
): Promise<{
  ok: boolean;
  reply?: string;
  needsChoice?: boolean;
  serviceability?: boolean;
}> {
  const search = await searchAndDisambiguate(userId, state, provider);
  if (!search.ok) return search;
  if ((state.pendingChoices ?? []).length > 0) {
    return { ok: true, needsChoice: true };
  }
  return assemblePreview(userId, state, provider);
}

async function placeOrder(
  userId: string,
  state: OrderState,
  provider: GroceryProvider,
): Promise<{ ok: boolean; reply?: string; serviceability?: boolean }> {
  if (!state.address?.id) {
    recordError(state, 'placing', 'no_address', 'address missing at place time');
    return { ok: false, reply: "Lost track of your delivery address — start over please." };
  }
  try {
    const placed = await provider.placeOrder(userId, {
      cartKey: state.preview?.cartKey,
      addressId: state.address.id,
      paymentMethod: 'cod',
    });
    state.order = { id: placed.orderId, placedAt: new Date().toISOString() };
    trace(state, 'placing', `placed id=${placed.orderId}`);
    return { ok: true };
  } catch (err) {
    if (err instanceof GroceryProviderError) {
      recordError(state, 'placing', 'place_failed', err.message);
      return {
        ok: false,
        serviceability: isServiceabilityError(err.message),
        reply: friendlyProviderError(
          err.message,
          'Couldn\'t place the order right now. Try again in a moment 🙏',
        ),
      };
    }
    throw err;
  }
}

// ─────────────────────────────────────────────────────────────────────────
// Orchestrator
// ─────────────────────────────────────────────────────────────────────────

export async function runOrderTurn(input: OrderTurnInput): Promise<WorkflowReply> {
  const { userId, message } = input;

  const loaded = await load(userId);
  const restart =
    !loaded ||
    loaded.state.phase === 'completed' ||
    loaded.state.phase === 'cancelled' ||
    loaded.state.phase === 'failed';

  let state: OrderState;
  let existingTask: AgentTask | undefined;
  if (restart) {
    state = blank();
    state.requests = input.orderItems ?? [];
    if (state.requests.length === 0) {
      // Classifier didn't extract anything (rare — e.g. it labeled this as
      // 'order' but couldn't pull a product). Bail out cleanly.
      return {
        text: 'What would you like to order? Tell me the items and quantities.',
        finished: true,
      };
    }
    state.phase = 'ensure_address';
    trace(state, 'ensure_address', `start requests=${JSON.stringify(state.requests)}`);
  } else {
    state = loaded!.state;
    existingTask = loaded!.task;
  }

  let provider: GroceryProvider;
  try {
    provider = await getGroceryProvider(userId);
  } catch (err) {
    if (err instanceof GroceryProviderNotConnectedError) {
      return {
        text: "You haven't connected Zepto yet. Visit aajkyakhaun.com/app to connect, then try again.",
        finished: true,
      };
    }
    throw err;
  }

  try {
    if (state.phase === 'ensure_address') {
      const r = await ensureAddress(userId, state, provider);
      if (r.kind === 'failed') {
        state.phase = 'failed';
        await save(userId, state, existingTask);
        return { text: r.reply, finished: true };
      }
      if (r.kind === 'awaiting') {
        state.phase = 'await_address_choice';
        await save(userId, state, existingTask);
        return { text: r.reply };
      }
      state.phase = 'preparing_preview';
    }

    if (state.phase === 'await_address_choice') {
      const choices = state.addressChoices ?? [];
      const pick = parseAddressChoice(message, choices.length);
      if (!pick) {
        return {
          text: `Reply with the number (1-${choices.length}) of the address to deliver to.`,
        };
      }
      const chosen = choices[pick - 1]!;
      await provider.selectAddress(userId, chosen.id);
      state.address = chosen;
      state.addressChoices = undefined;
      const persisted = state.savePickAsDefault === true;
      if (persisted) await persistDefaultAddress(userId, chosen.id);
      state.savePickAsDefault = undefined;
      trace(
        state,
        'await_address_choice',
        `picked ${chosen.id}${persisted ? ' (saved as default)' : ' (one-time)'}`,
      );
      state.phase = 'preparing_preview';
      // Fall through to preparing_preview on the same turn — better UX than
      // making the user wait another round-trip just to see the cart.
    }

    if (state.phase === 'preparing_preview') {
      return rebuildAndPresent(userId, state, provider, existingTask);
    }

    if (state.phase === 'await_line_choice') {
      const pending = state.pendingChoices?.[0];
      if (!pending) {
        // Defensive — no pending choice but we're in this phase. Try to
        // recover by re-running preview.
        return rebuildAndPresent(userId, state, provider, existingTask);
      }
      const choice = await classifyProductChoice(
        message,
        pending.candidates.map((c) => ({ name: c.name, pricePaise: c.pricePaise })),
      );
      if (choice.kind === 'cancel') {
        state.phase = 'cancelled';
        trace(state, 'cancelled', 'user cancelled at line choice');
        await save(userId, state, existingTask);
        return { text: 'Cancelled. No order placed 👍', finished: true };
      }
      if (choice.kind === 'noop') {
        return {
          text: `Reply with a number from the list above, or <i>skip</i> to drop "${escapeHtml(pending.query)}".`,
        };
      }
      if (choice.kind === 'skip') {
        state.unmatchedQueries.push(pending.query);
        state.pendingChoices = state.pendingChoices?.slice(1);
        trace(state, 'await_line_choice', `skipped ${pending.query}`);
      } else {
        const idx = choice.index - 1;
        const picked = pending.candidates[idx];
        if (!picked) {
          return {
            text: `That number isn't on the list. Pick 1 to ${pending.candidates.length}, or say <i>skip</i>.`,
          };
        }
        state.resolvedProducts = state.resolvedProducts ?? {};
        state.resolvedProducts[pending.requestIndex] = picked;
        state.pendingChoices = state.pendingChoices?.slice(1);
        trace(state, 'await_line_choice', `picked ${picked.name} for "${pending.query}"`);
      }

      // More to resolve?
      if ((state.pendingChoices ?? []).length > 0) {
        await save(userId, state, existingTask);
        return { text: presentLineChoiceReply(state) };
      }

      // All resolved — assemble cart + preview.
      const r = await assemblePreview(userId, state, provider);
      if (!r.ok) {
        if (r.serviceability) {
          return offerAddressChange(
            userId,
            state,
            provider,
            existingTask,
            r.reply ?? 'That address isn\'t serviceable right now.',
          );
        }
        state.phase = 'failed';
        await save(userId, state, existingTask);
        return { text: r.reply ?? 'Could not price the cart.', finished: true };
      }
      if (state.preview && !state.preview.deliverable) {
        return offerAddressChange(
          userId,
          state,
          provider,
          existingTask,
          presentUnserviceableReply(state),
        );
      }
      state.phase = 'await_confirm';
      await save(userId, state, existingTask);
      return { text: presentPreviewReply(state) };
    }

    if (state.phase === 'await_confirm') {
      const action = await classifyOrderAction(message, cartSummary(state));

      if (action.action === 'cancel') {
        state.phase = 'cancelled';
        trace(state, 'cancelled', 'user declined');
        await save(userId, state, existingTask);
        return { text: 'Cancelled. No order placed 👍', finished: true };
      }

      if (action.action === 'confirm') {
        state.phase = 'placing';
        const r = await placeOrder(userId, state, provider);
        if (!r.ok) {
          if (r.serviceability) {
            return offerAddressChange(
              userId,
              state,
              provider,
              existingTask,
              r.reply ?? 'That address isn\'t serviceable right now.',
            );
          }
          state.phase = 'failed';
          await save(userId, state, existingTask);
          return { text: r.reply ?? 'Order placement failed.', finished: true };
        }
        state.phase = 'completed';
        await save(userId, state, existingTask);
        return { text: placedReply(state), finished: true };
      }

      if (action.action === 'change_address') {
        return offerAddressChange(
          userId,
          state,
          provider,
          existingTask,
          'Sure — pick a different address for this order:',
        );
      }

      if (action.action === 'add') {
        state.requests = [...state.requests, ...action.items];
        trace(state, 'await_confirm', `add: +${action.items.length} items`);
        return rebuildAndPresent(userId, state, provider, existingTask);
      }

      if (action.action === 'remove') {
        const requestIndices = mapTargetLinesToRequestIndices(state, action.targetLines);
        if (requestIndices.length === 0) {
          return {
            text: 'I couldn\'t map that to a cart line. Mention the item name or its number from the list.',
          };
        }
        state.requests = state.requests.filter((_, i) => !requestIndices.includes(i));
        if (state.requests.length === 0) {
          state.phase = 'cancelled';
          trace(state, 'cancelled', 'all lines removed');
          await save(userId, state, existingTask);
          return {
            text: 'Cart is empty now. Tell me what to order when you\'re ready.',
            finished: true,
          };
        }
        trace(state, 'await_confirm', `remove: ${action.targetLines.join(',')}`);
        return rebuildAndPresent(userId, state, provider, existingTask);
      }

      if (action.action === 'set_quantity') {
        let zeroedAll = true;
        const toRemove = new Set<number>();
        for (const change of action.changes) {
          const cartIdx = change.lineIndex - 1;
          const cartLine = state.cart?.[cartIdx];
          if (!cartLine) continue;
          if (change.quantity === 0) {
            toRemove.add(cartLine.requestIndex);
          } else {
            const req = state.requests[cartLine.requestIndex];
            if (req) {
              req.quantity = change.quantity;
              zeroedAll = false;
            }
          }
        }
        if (toRemove.size > 0) {
          state.requests = state.requests.filter((_, i) => !toRemove.has(i));
        }
        if (state.requests.length === 0 && zeroedAll) {
          state.phase = 'cancelled';
          trace(state, 'cancelled', 'all qty set to 0');
          await save(userId, state, existingTask);
          return {
            text: 'Cart is empty now. Tell me what to order when you\'re ready.',
            finished: true,
          };
        }
        trace(state, 'await_confirm', `set_quantity changes=${action.changes.length}`);
        return rebuildAndPresent(userId, state, provider, existingTask);
      }

      // noop — gentle re-prompt without forcing a script.
      return {
        text:
          'Reply <b>yes</b> to place, <b>no</b> to cancel, or tell me to add / remove items ' +
          '(e.g. <i>add 1 hakka noodles</i>, <i>drop the chips</i>, <i>make it 2 ice creams</i>).',
      };
    }

    log.warn(`fell through phase=${state.phase}`, { userId });
    return { text: "Let me know what you'd like to order." };
  } catch (err) {
    log.error('unhandled order workflow error', err);
    state.phase = 'failed';
    recordError(state, state.phase, 'unhandled', err instanceof Error ? err.message : String(err));
    try { await save(userId, state, existingTask); } catch { /* ignore */ }
    return {
      text: 'Something went sideways while preparing the order. Try again in a minute 🙏',
      finished: true,
    };
  }
}

/** Diagnostic export. */
export async function getActiveOrderState(userId: string): Promise<OrderState | null> {
  const loaded = await load(userId);
  return loaded?.state ?? null;
}
