/**
 * Multi-item grocery order workflow.
 *
 * State machine:
 *   new → ensure_address → preparing_preview → await_confirm
 *     → placing → completed
 *                 ↓
 *               failed / cancelled
 *
 * Single confirmation: cart + fees + total are presented together. The
 * user reviews everything in one message and replies "yes" / "no". The
 * preview is generated by provider.previewOrder({ confirmOrder: false })
 * so fees come from the live cart, not estimates.
 *
 * One quantity-1 line per query in the user's request. Mid-cart edits
 * (remove, change, requantify) are not implemented in v1 — replying with
 * a new query list re-starts the flow.
 *
 * State persists in agent_tasks(type='order') with kind='order_v3' to
 * avoid colliding with the legacy zepto_order_v2 state shape.
 */

import { and, desc, eq, gt, inArray } from 'drizzle-orm';
import { db } from '../../config/database.js';
import { agentTasks, type AgentTask } from '../../db/schema.js';
import {
  type GroceryProvider,
  GroceryProviderError,
  GroceryProviderNotConnectedError,
  type OrderPreview,
  type ProductOption,
  type SearchGroup,
} from '../../providers/grocery/index.js';
import { getGroceryProvider } from '../../providers/grocery/index.js';
import { escapeHtml } from '../../utils/html.js';
import { createLogger } from '../../utils/logger.js';

const log = createLogger('order-workflow');

// ─────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────

export type Phase =
  | 'new'
  | 'ensure_address'
  | 'preparing_preview'
  | 'await_confirm'
  | 'placing'
  | 'completed'
  | 'failed'
  | 'cancelled';

export interface CartLineState {
  query: string;
  productVariantId: string;
  storeProductId: string;
  name: string;
  packSize: string;
  pricePaise: number;
  quantity: number;
}

export interface AddressState {
  id: string;
  label: string;
}

export interface PreviewState {
  cartKey?: string;
  subtotalPaise: number;
  deliveryFeePaise: number;
  handlingFeePaise: number;
  totalPaise: number;
  etaMinutes?: number;
}

export interface PhaseTrace { phase: Phase; action: string; at: string; }
export interface PhaseError { phase: Phase; code: string; message: string; at: string; }

export interface OrderState {
  kind: 'order_v3';
  phase: Phase;
  queries: string[];
  unmatchedQueries: string[];
  address?: AddressState;
  cart?: CartLineState[];
  preview?: PreviewState;
  order?: { id?: string; placedAt: string };
  errors: PhaseError[];
  trace: PhaseTrace[];
  updatedAt: string;
}

export interface OrderTurnInput {
  userId: string;
  message: string;
  /**
   * The intent classifier's orderQuery — a single phrase. We split it on
   * conjunctions/commas locally for multi-item. If undefined, the message
   * itself is treated as the query (rare path).
   */
  orderQuery?: string;
}

export interface WorkflowReply {
  text: string;
  finished?: boolean;
}

// ─────────────────────────────────────────────────────────────────────────
// Persistence
// ─────────────────────────────────────────────────────────────────────────

const WORKFLOW_TTL_MS = 30 * 60 * 1000;
const ACTIVE_STATUSES = ['active', 'waiting_user'] as const;

function blank(): OrderState {
  return {
    kind: 'order_v3',
    phase: 'new',
    queries: [],
    unmatchedQueries: [],
    errors: [],
    trace: [],
    updatedAt: new Date().toISOString(),
  };
}

function isOrderState(s: unknown): s is OrderState {
  return typeof s === 'object' && s !== null
    && (s as { kind?: unknown }).kind === 'order_v3';
}

async function load(userId: string): Promise<{ task: AgentTask; state: OrderState } | null> {
  const [task] = await db
    .select()
    .from(agentTasks)
    .where(
      and(
        eq(agentTasks.userId, userId),
        eq(agentTasks.type, 'order'),
        inArray(agentTasks.status, [...ACTIVE_STATUSES]),
        gt(agentTasks.expiresAt, new Date()),
      ),
    )
    .orderBy(desc(agentTasks.updatedAt))
    .limit(1);
  if (!task || !isOrderState(task.state)) return null;
  return { task, state: task.state };
}

async function save(userId: string, state: OrderState, existing?: AgentTask): Promise<void> {
  state.updatedAt = new Date().toISOString();
  const status =
    state.phase === 'completed' ? 'completed'
      : state.phase === 'cancelled' ? 'cancelled'
      : state.phase === 'failed' ? 'failed'
      : 'waiting_user';
  const expiresAt = status === 'waiting_user' ? new Date(Date.now() + WORKFLOW_TTL_MS) : null;

  if (existing) {
    await db
      .update(agentTasks)
      .set({
        status,
        state,
        expiresAt: expiresAt ?? existing.expiresAt,
        updatedAt: new Date(),
      })
      .where(eq(agentTasks.id, existing.id));
    return;
  }
  await db.insert(agentTasks).values({
    userId,
    type: 'order',
    status,
    state,
    expiresAt: expiresAt ?? new Date(Date.now() + WORKFLOW_TTL_MS),
  });
}

function trace(state: OrderState, phase: Phase, action: string): void {
  state.trace.push({ phase, action, at: new Date().toISOString() });
  if (state.trace.length > 40) state.trace.splice(0, state.trace.length - 40);
}
function recordError(state: OrderState, phase: Phase, code: string, message: string): void {
  state.errors.push({ phase, code, message: message.slice(0, 500), at: new Date().toISOString() });
  log.warn(`[phase=${phase}] ${code}: ${message}`);
}

// ─────────────────────────────────────────────────────────────────────────
// Intent / reply parsing
// ─────────────────────────────────────────────────────────────────────────

const CONFIRM_RE = /^(yes|y|yep|yeah|confirm|go ahead|order it|place it|do it|haan|haan ji|han|haa|sure|ok|okay|chalo|kar do|mangwa do|manga do|✅)\b/i;
const CANCEL_RE = /^(no|n|nope|nah|cancel|stop|don'?t|leave it|rehne do|mat karo|nahi|nahin|abort|✗|❌)\b/i;

function parseConfirm(text: string): 'yes' | 'no' | null {
  const t = text.trim();
  if (CONFIRM_RE.test(t)) return 'yes';
  if (CANCEL_RE.test(t)) return 'no';
  return null;
}

/** Split "milk, bread and eggs" → ["milk", "bread", "eggs"]. */
export function splitQueries(raw: string): string[] {
  return raw
    .split(/\s*[,;]\s*|\s+(?:and|aur|&)\s+/i)
    .map((s) => s.trim())
    .filter((s) => s.length > 0)
    .slice(0, 12); // safety cap
}

// ─────────────────────────────────────────────────────────────────────────
// Reply formatters
// ─────────────────────────────────────────────────────────────────────────

function rupees(paise: number): string {
  if (paise === 0) return '₹0';
  return `₹${(paise / 100).toFixed(paise % 100 === 0 ? 0 : 2)}`;
}

function presentPreviewReply(state: OrderState): string {
  const cart = state.cart ?? [];
  const pre = state.preview;
  if (!pre) return 'Preparing preview…';

  const lines = cart.map((l, i) => {
    const qty = l.quantity > 1 ? ` × ${l.quantity}` : '';
    const sub = `${escapeHtml(l.name)}${qty}`;
    const meta: string[] = [];
    if (l.packSize) meta.push(escapeHtml(l.packSize));
    if (l.pricePaise > 0) meta.push(`<b>${rupees(l.pricePaise * l.quantity)}</b>`);
    return `${i + 1}. ${sub}${meta.length ? ' · ' + meta.join(' · ') : ''}`;
  });

  const addr = state.address?.label ? ` to ${escapeHtml(state.address.label)}` : '';
  const eta = pre.etaMinutes ? `\n⏱ ETA ~${pre.etaMinutes} min` : '';
  const unmatched = state.unmatchedQueries.length
    ? `\n\n⚠️ Couldn't find: ${state.unmatchedQueries.map(escapeHtml).join(', ')}`
    : '';

  return [
    `<b>Cart preview</b>${addr}:`,
    '',
    lines.join('\n'),
    '',
    `Subtotal: <b>${rupees(pre.subtotalPaise)}</b>`,
    `Delivery: ${rupees(pre.deliveryFeePaise)}`,
    `Handling: ${rupees(pre.handlingFeePaise)}`,
    `<b>Total: ${rupees(pre.totalPaise)}</b> · COD${eta}${unmatched}`,
    '',
    'Reply <b>yes</b> to place, <b>no</b> to cancel.',
  ].join('\n');
}

function placedReply(state: OrderState): string {
  const total = state.preview?.totalPaise;
  const id = state.order?.id;
  const idLine = id ? `\nOrder id: <code>${escapeHtml(id)}</code>` : '';
  const totalLine = total ? ` for <b>${rupees(total)}</b>` : '';
  return `✅ Order placed${totalLine} on COD.${idLine}\n\nI'll update your pantry once it arrives 🍽️`;
}

// ─────────────────────────────────────────────────────────────────────────
// Phases
// ─────────────────────────────────────────────────────────────────────────

async function ensureAddress(
  userId: string,
  state: OrderState,
  provider: GroceryProvider,
): Promise<{ ok: boolean; reply?: string }> {
  if (state.address?.id) return { ok: true };
  const addresses = await provider.listAddresses(userId);
  if (addresses.length === 0) {
    recordError(state, 'ensure_address', 'no_address', 'no saved addresses');
    return {
      ok: false,
      reply: 'You have no saved delivery address on Zepto. Open the Zepto app, add one, then come back 🙏',
    };
  }
  const chosen = addresses.find((a) => a.isDefault) ?? addresses[0]!;
  await provider.selectAddress(userId, chosen.id);
  state.address = { id: chosen.id, label: chosen.label };
  trace(state, 'ensure_address', `selected ${chosen.id}`);
  return { ok: true };
}

function pickBestProduct(group: SearchGroup): ProductOption | null {
  for (const p of group.products) {
    if (p.available && p.productVariantId && p.storeProductId) return p;
  }
  return group.products[0] ?? null;
}

async function buildCartAndPreview(
  userId: string,
  state: OrderState,
  provider: GroceryProvider,
): Promise<{ ok: boolean; reply?: string }> {
  if (state.queries.length === 0) {
    recordError(state, 'preparing_preview', 'no_queries', 'no queries to search');
    return { ok: false, reply: 'What would you like to order?' };
  }

  // Search.
  const groups = await provider.searchMany(userId, state.queries);
  const cart: CartLineState[] = [];
  const unmatched: string[] = [];
  for (const g of groups) {
    const top = pickBestProduct(g);
    if (!top) {
      unmatched.push(g.query);
      continue;
    }
    cart.push({
      query: g.query,
      productVariantId: top.productVariantId,
      storeProductId: top.storeProductId,
      name: top.name,
      packSize: top.packSize,
      pricePaise: top.pricePaise,
      quantity: 1,
    });
  }
  state.cart = cart;
  state.unmatchedQueries = unmatched;
  trace(state, 'preparing_preview', `cart=${cart.length} unmatched=${unmatched.length}`);

  if (cart.length === 0) {
    recordError(state, 'preparing_preview', 'all_unmatched', `nothing matched: ${unmatched.join(', ')}`);
    return {
      ok: false,
      reply: `Couldn't find any of: <b>${unmatched.map(escapeHtml).join(', ')}</b>. Try a more specific name or check spelling.`,
    };
  }

  // Stage cart on the provider.
  const cartResult = await provider.upsertCart(
    userId,
    cart.map((l) => ({
      productVariantId: l.productVariantId,
      storeProductId: l.storeProductId,
      quantity: l.quantity,
      name: l.name,
      pricePaise: l.pricePaise,
    })),
    { replace: true },
  );

  // Live preview with fees.
  let preview: OrderPreview;
  try {
    preview = await provider.previewOrder(userId, {
      addressId: state.address!.id,
      paymentMethod: 'cod',
    });
  } catch (err) {
    if (err instanceof GroceryProviderError) {
      recordError(state, 'preparing_preview', 'preview_failed', err.message);
      return { ok: false, reply: `Couldn't price the cart: ${escapeHtml(err.message)}` };
    }
    throw err;
  }

  state.preview = {
    cartKey: cartResult.cartKey ?? preview.cartKey,
    subtotalPaise: preview.subtotalPaise,
    deliveryFeePaise: preview.deliveryFeePaise,
    handlingFeePaise: preview.handlingFeePaise,
    totalPaise: preview.totalPaise,
    etaMinutes: preview.etaMinutes,
  };
  trace(state, 'preparing_preview', `total=${preview.totalPaise}`);
  return { ok: true };
}

async function placeOrder(
  userId: string,
  state: OrderState,
  provider: GroceryProvider,
): Promise<{ ok: boolean; reply?: string }> {
  if (!state.address?.id) {
    recordError(state, 'placing', 'no_address', 'address missing at place time');
    return { ok: false, reply: "Lost track of your delivery address — start over please." };
  }
  try {
    const placed = await provider.placeOrder(userId, {
      cartKey: state.preview?.cartKey,
      addressId: state.address.id,
      paymentMethod: 'cod',
    });
    state.order = { id: placed.orderId, placedAt: new Date().toISOString() };
    trace(state, 'placing', `placed id=${placed.orderId}`);
    return { ok: true };
  } catch (err) {
    if (err instanceof GroceryProviderError) {
      recordError(state, 'placing', 'place_failed', err.message);
      return { ok: false, reply: `Order placement failed: ${escapeHtml(err.message)}` };
    }
    throw err;
  }
}

// ─────────────────────────────────────────────────────────────────────────
// Orchestrator
// ─────────────────────────────────────────────────────────────────────────

export async function runOrderTurn(input: OrderTurnInput): Promise<WorkflowReply> {
  const { userId, message } = input;

  // Hard cancel at any point.
  if (parseConfirm(message) === 'no' && message.trim().length <= 15) {
    const existing = await load(userId);
    if (existing) {
      existing.state.phase = 'cancelled';
      trace(existing.state, 'cancelled', 'user cancelled');
      await save(userId, existing.state, existing.task);
    }
    return { text: 'Cancelled. No order placed 👍', finished: true };
  }

  const loaded = await load(userId);
  const restart =
    !loaded ||
    loaded.state.phase === 'completed' ||
    loaded.state.phase === 'cancelled' ||
    loaded.state.phase === 'failed';

  let state: OrderState;
  let existingTask: AgentTask | undefined;
  if (restart) {
    state = blank();
    const queries = splitQueries(input.orderQuery ?? message);
    state.queries = queries;
    state.phase = 'ensure_address';
    trace(state, 'ensure_address', `start queries=${JSON.stringify(queries)}`);
  } else {
    state = loaded!.state;
    existingTask = loaded!.task;
  }

  let provider: GroceryProvider;
  try {
    provider = await getGroceryProvider(userId);
  } catch (err) {
    if (err instanceof GroceryProviderNotConnectedError) {
      return {
        text: "You haven't connected Zepto yet. Visit aajkyakhaun.com/app to connect, then try again.",
        finished: true,
      };
    }
    throw err;
  }

  try {
    if (state.phase === 'ensure_address') {
      const r = await ensureAddress(userId, state, provider);
      if (!r.ok) {
        state.phase = 'failed';
        await save(userId, state, existingTask);
        return { text: r.reply ?? 'Address step failed.', finished: true };
      }
      state.phase = 'preparing_preview';
    }

    if (state.phase === 'preparing_preview') {
      const r = await buildCartAndPreview(userId, state, provider);
      if (!r.ok) {
        state.phase = 'failed';
        await save(userId, state, existingTask);
        return { text: r.reply ?? 'Could not prepare preview.', finished: true };
      }
      state.phase = 'await_confirm';
      await save(userId, state, existingTask);
      return { text: presentPreviewReply(state) };
    }

    if (state.phase === 'await_confirm') {
      const decision = parseConfirm(message);
      if (decision === null) {
        return { text: 'Reply <b>yes</b> to place this order or <b>no</b> to cancel.' };
      }
      if (decision === 'no') {
        state.phase = 'cancelled';
        trace(state, 'cancelled', 'user declined');
        await save(userId, state, existingTask);
        return { text: 'Cancelled. No order placed 👍', finished: true };
      }
      state.phase = 'placing';
      const r = await placeOrder(userId, state, provider);
      if (!r.ok) {
        state.phase = 'failed';
        await save(userId, state, existingTask);
        return { text: r.reply ?? 'Order placement failed.', finished: true };
      }
      state.phase = 'completed';
      await save(userId, state, existingTask);
      return { text: placedReply(state), finished: true };
    }

    log.warn(`fell through phase=${state.phase}`, { userId });
    return { text: "Let me know what you'd like to order." };
  } catch (err) {
    log.error('unhandled order workflow error', err);
    state.phase = 'failed';
    recordError(state, state.phase, 'unhandled', err instanceof Error ? err.message : String(err));
    try { await save(userId, state, existingTask); } catch { /* ignore */ }
    return {
      text: 'Something went sideways while preparing the order. Try again in a minute 🙏',
      finished: true,
    };
  }
}

/** Diagnostic export. */
export async function getActiveOrderState(userId: string): Promise<OrderState | null> {
  const loaded = await load(userId);
  return loaded?.state ?? null;
}
